import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Layout from '../components/Layout'
import PublicNav from '../components/PublicNav'
import { useAuth } from '../context/AuthContext'

export default function GlobalSearchPage(){
  const {user}=useAuth(); const navigate=useNavigate(); const [query,setQuery]=useState(''); const [events,setEvents]=useState([]); const [organizers,setOrganizers]=useState([]); const [providers,setProviders]=useState([])
  useEffect(()=>{let a=()=>{},b=()=>{},c=()=>{};import('../utils/firestore-sync').then(({listenEvents,listenOrganizerProfiles,listenProviders})=>{a=listenEvents(setEvents);b=listenOrganizerProfiles(setOrganizers);c=listenProviders(setProviders)}).catch(()=>{});return()=>{a();b();c()}},[])
  const q=query.trim().toLowerCase(); const contains=(...values)=>q&&values.filter(Boolean).join(' ').toLowerCase().includes(q)
  const results=useMemo(()=>({events:q?events.filter(e=>!e.isPrivate&&contains(e.name,e.city,e.category)).slice(0,8):[],organizers:q?organizers.filter(o=>contains(o.publicName,o.city,o.country,...(o.vibes||[]))).slice(0,8):[],providers:q?providers.filter(p=>contains(p.name,p.location,p.description)).slice(0,8):[]}),[q,events,organizers,providers])
  const content=<div style={{minHeight:'100vh',background:'#04040b',color:'#fff'}}>{!user&&<PublicNav/>}<main style={{maxWidth:920,margin:'0 auto',padding:'48px 20px 100px'}}><h1 style={{font:'clamp(48px,8vw,76px) Bebas Neue',margin:'0 0 20px'}}>Rechercher</h1><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Événement, organisateur, prestataire, ville…" style={{width:'100%',boxSizing:'border-box',padding:'17px 18px',background:'rgba(255,255,255,.04)',border:'1px solid rgba(255,255,255,.16)',color:'#fff',fontSize:15,outline:'none'}}/>{!q?<p style={{color:'rgba(255,255,255,.42)',marginTop:24}}>Saisis au moins un mot pour lancer la recherche.</p>:<div style={{display:'grid',gap:32,marginTop:34}}>{[['Événements',results.events,item=>`/evenements/${item.id}`,item=>item.name],['Organisateurs',results.organizers,item=>`/organisateurs/${item.slug}`,item=>item.publicName],['Prestataires',results.providers,item=>`/prestataires/${item.userId}`,item=>item.name]].map(([title,items,pathOf,labelOf])=><section key={title}><h2 style={{font:'30px Bebas Neue',margin:'0 0 10px'}}>{title}</h2>{items.length===0?<p style={{color:'rgba(255,255,255,.35)',fontSize:12}}>Aucun résultat.</p>:<div style={{display:'grid',gap:7}}>{items.map(item=><button key={item.id||item.userId} onClick={()=>navigate(pathOf(item))} style={{padding:'13px 14px',display:'flex',justifyContent:'space-between',gap:12,background:'rgba(255,255,255,.025)',border:'1px solid rgba(255,255,255,.09)',color:'#fff',cursor:'pointer',textAlign:'left'}}><span>{labelOf(item)}</span><span style={{color:'#4ee8c8'}}>→</span></button>)}</div>}</section>)}</div>}</main></div>
  return user?<Layout>{content}</Layout>:content
}
